name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go 1.21.5
        uses: actions/setup-go@v2
        with:
            go-version: '1.21.5'

      - name: Build for Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o main ./...

      - name: Zip the executable
        run: zip main.zip main

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name hello-world-lambda --zip-file fileb://publish.zip --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET }}"